local data = require ("main.data")

function init(self)
	self.pos = go.get_position()
	self.theta = 0
end

function update(self, dt)
	self.theta = self.theta + 0.025
	self.pos.y = self.pos.y + (math.sin(self.theta))
	
	go.set_position(self.pos)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("bullet_hit") then
		particlefx.play("#particlefx")
		msg.post("main:/sound#mine", "play_sound", {gain = 1.0})
		go.delete()
	end
end

