local data = require "main.data"

local function disablenode (self, node)
	gui.set_enabled(node, false)
end

local function hide(self)
	gui.animate(gui.get_node("shutter_top"), gui.PROP_POSITION, vmath.vector4(640, 680, 0, 0), gui.EASING_LINEAR, 0.4, 0, disablenode)
	gui.animate(gui.get_node("shutter_bottom"), gui.PROP_POSITION, vmath.vector4(640, 0, 0, 0), gui.EASING_LINEAR, 0.4, 0, disablenode)
end

function init(self)
	gui.set_render_order(14)
	hide(self)
end