local data = require ("main.data")

function addflak(self)
	local x = data.playerpos.x / 16
	x = x + math.random(1 + 20)
	local y = math.random(4,16)
	if tilemap.get_tile("level#map", "main", x, y) == 0 then	
		tilemap.set_tile("level#map", "main", x, y, math.random(26,32))	
		go.set_position(vmath.vector3((x * 16) - 8, (y * 16) - 8, 0))
		particlefx.play("#pfx")
		msg.post("main:/sound#flak", "play_sound", {gain = 0.35})		
	end
end

function update(self, dt)
	if data.scrollpos.x > (80 * 16) and
	   data.scrollpos.x < (530 * 16) and 
	   math.random(1, 30) == 1 and 
	   data.state == data.STATE_PLAYING then
		addflak(self)
	end
end
