local data = require "main.data"

go.property("move", vmath.vector3())

function init(self)
	local r = math.atan2(self.move.y, self.move.x)
	go.set_rotation(vmath.quat_rotation_z(r))
end

function update(self, dt)
	local pos = go.get_position()
	pos = pos + self.move
	go.set_position(pos)

	if pos.x < -16 then go.delete()
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		go.delete()
	end
end
