local data = require ("main.data")

function init(self)
	local node = gui.get_node("message")
	gui.set_color(node, vmath.vector4(1,1,1,0))
 	gui.set_enabled(node, false)
end

function scalebar(node, val, max)
	local s = (val / max)
	
	if s < 0 then s = 0 end
	
	gui.set_scale(node, vmath.vector3(s, 1, 0))
	
	if s <= 0.2 then gui.set_color(node, vmath.vector4(0.8, 0, 0, 1))
	else gui.set_color(node, vmath.vector4(0, 0.8, 0, 1))
	end
end

function update(self, dt)
	scalebar(gui.get_node("fuelbar"), data.fuel, 100)
	scalebar(gui.get_node("hullbar"), data.hull, 100)
	scalebar(gui.get_node("speedbar"), data.speed, data.TOP_SPEED)
	scalebar(gui.get_node("rocketsbar"), data.rockets, data.MAX_ROCKETS)
	scalebar(gui.get_node("bombsbar"), data.bombs, data.MAX_BOMBS)
	
	gui.set_text(gui.get_node("scoretext"), string.format("%07d", data.score))
end

local function gameover(self)
 	gui.set_text(gui.get_node("central"), "MISSION FAILED")
	local node = gui.get_node("message")
 	gui.set_enabled(node, true)
	gui.animate(node, gui.PROP_COLOR, vmath.vector4(0,0,0,1), gui.EASING_INOUTQUAD, 0.5)
end

local function completed(self)
 	gui.set_text(gui.get_node("central"), "MISSION COMPLETED")
	local node = gui.get_node("message")
 	gui.set_enabled(node, true)
	gui.animate(node, gui.PROP_COLOR, vmath.vector4(0,0,0,1), gui.EASING_INOUTQUAD, 0.5)
end

local function processclick(self, x, y) 
	if gui.pick_node(gui.get_node("button"), x, y) and data.state ~= data.STATE_MENU then
		msg.post("main:/handler", "show_menu")
	end
end 

function on_message(self, message_id, message, sender)
	if message_id == hash("gameover") then	
		gameover(self)
	elseif message_id == hash("completed") then	
		completed(self)
	elseif message_id == hash("clicktap") then
		processclick(self, message.x, message.y)
	end
end

