local function disablenode (self, node)
	gui.set_enabled(node, false)
end

local function hide(self)
	gui.animate(gui.get_node("shutter_top"), gui.PROP_POSITION, vmath.vector3(640,720,0), gui.EASING_INOUTQUAD, 0.5, 0, disablenode)
	gui.animate(gui.get_node("shutter_bottom"), gui.PROP_POSITION, vmath.vector3(640,0,0), gui.EASING_INOUTQUAD, 0.5, 0, disablenode)
end

function init(self)
	hide(self)
end