function init(self)
	self.pos = vmath.vector3(0,0,0)
end

function update(self, dt)

	local p = vmath.vector3(72, 0, 0)

	p.y = self.pos.y / 2
	
	while self.pos.y - p.y < 120 do p.y = p.y - 240	end
	while self.pos.y - p.y > 240 do	p.y = p.y + 240	end

	go.set_position(p)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("pos") then
		self.pos = message.pos
		self.pos.z = -1
	end
end

