local data = require "main.data"

local SPEED = 1

go.property("move", vmath.vector3())

function init(self)
	if self.move.x < 0 then
		sprite.set_hflip("#sprite", true)
	end 
end

function update(self, dt)
	if data.state == data.STATE_PLAYING then
		local pos = go.get_position()
		pos.z = 0.2
		go.set_position(pos + self.move)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collision_response") then
		go.delete()
	end
end

