local data = require "main.data"

local TIME = 1

go.property("move", vmath.vector3())

function init(self)
	self.time = 0
	if self.move.x > 0 then self.time = TIME/2
	end
end

function update(self, dt)
	if data.state == data.STATE_PLAYING then
		if data.onscreen(go.get_position(), 0) then
			self.time = self.time + dt
			if self.time > TIME then
				self.time = 0
				factory.create("#arrow-factory", nil, nil, {move = self.move})
				sound.play("main:/sound#dart")
			end
		end
	end
end
