local data = require ("main.data")

function init(self)
	local node = gui.get_node("menu")
 	gui.set_position(node, vmath.vector3(0, 0, 0))
	msg.post(".", "acquire_input_focus")
	data.state = data.STATE_MENU
	
    local sysinfo = sys.get_sys_info()
    if sysinfo.system_name == "Android" then
    	gui.set_enabled(gui.get_node("controlsbox"), false)
		local pos = gui.get_position(gui.get_node("startbox"))
		pos.x = 640
		gui.set_position(gui.get_node("startbox"), pos)
	end	 
end

local function show(self)
	local node = gui.get_node("menu")
	gui.animate(gui.get_node("menu"), gui.PROP_POSITION, vmath.vector3(0, 0, 0), gui.EASING_INOUTQUAD, 0.5)
 	data.state = data.STATE_MENU
end

local function hide(self)
	local node = gui.get_node("menu")
	gui.animate(gui.get_node("menu"), gui.PROP_POSITION, vmath.vector3(-1280, 0, 0), gui.EASING_INOUTQUAD, 0.5)
end

local function processclick(self, x, y) 
	if gui.pick_node(gui.get_node("startbox"), x, y) then
		msg.post("main:/handler", "show_game")
	elseif gui.pick_node(gui.get_node("controlsbox"), x, y) then
		hide(self)
		msg.post("#controls", "show", {})
	elseif gui.pick_node(gui.get_node("exit"), x, y) then
		msg.post("@system:", "exit", {code = 0})	
	end
end 

function on_input(self, action_id, action)
	if action.pressed and data.state == data.STATE_MENU then			
		if action_id == hash("clicktap") then
			processclick(self, action.x, action.y)
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show") then
	 	show(self)
	end
end