go.property ("large", true)

local MARGIN = 70

function init(self)
	self.speed = math.random(100,200) / 100
	if self.large then self.speed = self.speed * 0.06
	else self.speed = self.speed * 0.03
	end
end

function update(self, dt)
	local pos = go.get_position()
	pos.x = pos.x - self.speed
	if pos.x < -MARGIN then
		pos.x = (320 + MARGIN)
		pos.y = math.random(130,160)
	end
	go.set_position(pos)
end
