local data = require "main.data"

function on_message(self, message_id, message, sender)
	if message_id == hash("explode") then
		go.set_position(data.snap(message.pos))
		particlefx.play("#explode")
		sound.play(string.format("main:/sound#exp%d", math.random(1,3)))
	elseif message_id == hash("explode_large") then
		go.set_position(data.snap(message.pos))
		particlefx.play("#explode_large")
		sound.play("main:/sound#bigbang")
	end
end

