components {
  id: "crate"
  component: "/game/object/crate.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"crate\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/core/game.tilesource\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "co"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.3\n"
  "restitution: 0.0\n"
  "group: \"crate\"\n"
  "mask: \"player\"\n"
  "mask: \"world\"\n"
  "mask: \"fireball\"\n"
  "mask: \"crate\"\n"
  "mask: \"teleport\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 7.0\n"
  "  data: 8.0\n"
  "  data: 10.0\n"
  "}\n"
  "locked_rotation: true\n"
  ""
}
