local data = require ("main.data")

function init(self)
	msg.post("#camera", "acquire_camera_focus")
	msg.post("@render:", "clear_color", {color = vmath.vector4(30/255, 129/255, 170/255, 0)})
	self.pos = go.get_world_position()
end

function update(self, dt)
	local p = self.pos - data.offset
	go.set_position(p)
	data.scrollpos = p
end

function on_message(self, message_id, message, sender)
	if message_id == hash("look_at") then	
		self.pos = message.position
	end
end

