local data = require "main.data"

local function disablenode (self, node)
	gui.set_enabled(node, false)
end

local function hide(self)
	gui.animate(gui.get_node("shutter_top"), gui.PROP_POSITION, vmath.vector4(0, 720, 0, 0), gui.EASING_LINEAR, 0.25, 0.25)
	gui.animate(gui.get_node("shutter_bottom"), gui.PROP_POSITION, vmath.vector4(0, 0, 0, 0), gui.EASING_LINEAR, 0.25, 0.25, disablenode)
end

function init(self)
	hide(self)
	gui.set_render_order(11)
end