local data = require ("main.data")

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "clear_color", {color = vmath.vector4(218/255, 243/255, 236/255, 0)})
	data.state = data.STATE_MENU
end

function on_input(self, action_id, action)
	if data.state == data.STATE_MENU then
		if action_id == hash("jump") and action.pressed then
			data.state = data.STATE_PLAYING
			msg.post("main:/handler", "show_game")
		end
	end
end