components {
  id: "script"
  component: "/game/object/exit.script"
}
components {
  id: "pfx"
  component: "/game/object/exit.particlefx"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"exit\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/core/game48.tilesource\"\n"
  "}\n"
  ""
  position {
    y: 8.0
  }
}
embedded_components {
  id: "co-field"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"exit\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 6.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 6.0\n"
  "  data: 6.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "co"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"world\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -10.0\n"
  "      y: -4.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.25881904\n"
  "      w: 0.9659258\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 10.0\n"
  "      y: -4.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.25881904\n"
  "      w: 0.9659258\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -2.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 3\n"
  "  }\n"
  "  data: 4.0\n"
  "  data: 2.0\n"
  "  data: 10.0\n"
  "  data: 4.0\n"
  "  data: 2.0\n"
  "  data: 10.0\n"
  "  data: 7.0\n"
  "  data: 2.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
