local data = require ("main.data")

local function disablenode (self, node)
	gui.set_enabled(gui.get_node("box"), false)
end

function init(self)
	gui.set_text(gui.get_node("word"), "")
	gui.animate(gui.get_node("shutter"), gui.PROP_POSITION, vmath.vector4(640, 50, 0, 0), gui.EASING_INOUTQUAD, 0.5, 0, disablenode)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("word") then
		gui.set_text(gui.get_node("word"), string.upper(message.text))
	end
end

