local data = require "main.data"
local ui = require "main.ui"

function init(self)
	self.node = gui.get_node("container")
	ui.init(self.node)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show") then
		ui.show(self.node)
		data.state = data.STATE_CLEAR
		local time = os.clock() - data.time
		local text = "YOUR TIME: "..data.ms2str(time)
		gui.set_text(gui.get_node("time"), text)
	end
end
