function on_message(self, message_id, message, sender)
	if message_id == hash("explode") then
		go.set_position(message.pos)
		local text = "main:/sound#exp"..tostring(math.random(1,3))
		particlefx.play("#explode")
		sound.play(text)
	elseif message_id == hash("splash") then
		go.set_position(message.pos)
		particlefx.play("#explode")
		particlefx.play("#splash")
		sound.play("main:/sound#splash")
	end
end