function on_message(self, message_id, message, sender)
	if message_id == hash("fade_in") then
		node = gui.get_node("fade")
		gui.animate(node, gui.PROP_COLOR, vmath.vector4(14/255, 12/255, 25/255, 0), gui.EASING_INOUTQUAD, 0.2)
	elseif message_id == hash("fade_out") then
		node = gui.get_node("fade")
		gui.animate(node, gui.PROP_COLOR, vmath.vector4(14/255, 12/255, 25/255, 1), gui.EASING_INOUTQUAD, 0.2)
	end
end

