local data = require ("main.data")

local DROP = 150

go.property("speed", 100)

function init(self)
	self.life = 70
	
	self.velocity = vmath.vector3(self.speed, -DROP, 0)
end

local function destroy(self)
	go.delete()
end

function update(self, dt)
	self.life = self.life - 1
	if self.life < 1 then
		destroy(self)
	end

	self.velocity.y = self.velocity.y - (DROP * dt)
	local p = go.get_position() + (self.velocity * dt)
	if tilecheck(self) then destroy(self) end
	go.set_position(p)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") then
		if message.group == hash("enemy") then
			destroy(self)
		end
	end
end
