local data = require ("main.data")

local speed = 10

function init(self)
	self.life = 50
	self.velocity = vmath.vector3(speed, 0, 0)
	particlefx.play("#pfx")
end

local function destroy(self)
	particlefx.stop("#pfx")
	go.delete()
end

function update(self, dt)
	self.life = self.life - 1
	if self.life < 1 then
		destroy(self)
	end

	local p = go.get_position() + self.velocity
	if tilecheck(self) then destroy(self) end
	go.set_position(p)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") then
		if message.group == hash("enemy") then
			destroy(self)
		end
	end
end

