local data = require ("main.data")

local function powerbar(self, power)
	local p = power
	if p > 10 then p = 10 end
	gui.set_scale(gui.get_node("mask"), vmath.vector3(1-(p/10), 1, 1))
end

function update(self, dt)
	gui.set_text(gui.get_node("lives"), tostring(data.lives))
end

function on_message(self, message_id, message, sender)
	if message_id == hash("power") then powerbar(self, message.power)
	end
end