local data = require("main.data")

local SPEED = 2

function init(self)
	self.vel = vmath.vector3(SPEED, 0, 0)
	local pos = go.get_position()
	pos.z = pos.z - 0.1
	go.set_position(pos)
end

function update(self, dt)
	self.vel.x = self.vel.x / 1.03
	self.vel.y = self.vel.y - 0.1
	local pos = go.get_position()
	pos = pos + self.vel
	go.set_position(pos)
	if not data.onscreen(pos, data.TILE_SIZE) then go.delete() end
end

