components {
  id: "player"
  component: "/game/player/player.script"
}
components {
  id: "dust"
  component: "/game/player/dust.particlefx"
  position {
    y: -8.0
  }
}
components {
  id: "item"
  component: "/game/player/item.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"run\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/game/core/game.tilesource\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "co"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"player\"\n"
  "mask: \"world\"\n"
  "mask: \"lift\"\n"
  "mask: \"enemy\"\n"
  "mask: \"platform\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: 0.5\n"
  "      y: -3.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: 0.5\n"
  "      y: 3.5\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 1\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 0.5\n"
  "      y: 1.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 2\n"
  "    count: 3\n"
  "  }\n"
  "  data: 5.0\n"
  "  data: 3.5\n"
  "  data: 3.5\n"
  "  data: 2.0\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
