local data = require "main.data"

go.property("size", 16)

local SPEED = 10
local SHOT_SPEED = 100
local FREQ = 0.05

function init(self)
	self.ang = 0
	self.time = -1
	self.total = 50
end

local function move(self, dt)
	local pos = go.get_position()
	local v = vmath.vector3(data.SCR_W / 2, data.SCR_H / 2, 0) - pos

	v = vmath.normalize(v)
	pos = pos + (v * SPEED * dt)
	go.set_position(pos)
end

local function dead(self)
	go.set_rotation(vmath.quat_rotation_z(0))
	particlefx.play("#pfx")
	sound.play("main:/sound#explosion")
	go.delete()
end

local function fire(self, dt)
	if self.time ~= -1 then
		self.ang = self.ang + (dt * 10)
		self.time = self.time - dt
		if self.time < 0 then
			self.time = FREQ
			self.total = self.total - 1
			if self.total <= 0 then dead(self) end
			local v = vmath.vector3(math.cos(self.ang), math.sin(self.ang), 0)
			v = vmath.normalize(v) * SHOT_SPEED
			factory.create("#shot_factory", nil, vmath.quat_rotation_z(self.ang), {move = v})
		end
	end
end

function update(self, dt)
	move(self, dt)
	fire(self, dt)
end

local function detonate(self)
	self.time = FREQ
	msg.post("#co", "disable")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") then
		if message.other_group == hash("shot") or message.other_group == hash("player") then
			detonate(self)
		end
	end
end

