local data = require ("main.data")

function init(self)
	self.node = gui.get_node("container")
	gui.set_enabled(self.node, false)
	gui.set_color(self.node, vmath.vector4(1,1,1,0))
end

local function show(self)
	gui.set_enabled(self.node, true)
	gui.animate(self.node, gui.PROP_COLOR, vmath.vector4(1,1,1,1), gui.EASING_INOUTQUAD, 0.5)
	data.state = data.STATE_COMPLETE
end

function on_message(self, message_id, message, sender)
if message_id == hash("show") then show(self) end
end
