function init(self)
	msg.post("#camera", "acquire_camera_focus")
	self.pos = go.get_world_position()
	self.offset = vmath.vector3 (160, 90, 0)
end

function update(self, dt)
	self.pos = self.pos - self.offset
	go.set_position(self.pos)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("look_at") then
		self.pos = message.position
		msg.post("bg", "position", {pos = self.pos})
	end
end

