local data = require "main.data"

local function addacid(self, pos)
	table.insert(self.acid, pos)
end

local function parse(self)
	sx, sy, w, h = tilemap.get_bounds("#tilemap")

	data.bounds = vmath.vector4((sx - 1) * data.TILE_SIZE, (sy - 1) * data.TILE_SIZE, ((sx + w - 1) * data.TILE_SIZE) - data.SCR_W, ((sy + h - 1) * data.TILE_SIZE) - data.SCR_H)
	
	for y = sy, h+sy-1 do
		for x = sx, w+sx-1 do
			local t = tilemap.get_tile("#tilemap", "world", x, y)
			if t == 1 then
				tilemap.set_tile("#tilemap", "world", x, y, 0)
				msg.post("common/player", "position", {pos = data.tile2world(vmath.vector3(x, y, -0.1))})
			elseif t == 13 then
				addacid(self, vmath.vector3(x, y, 0))
			elseif t == 54 then
				if math.random(1,2) == 1 then
					tilemap.set_tile("#tilemap", "world", x, y, math.random(17,24))
				end
			end
		end
	end
end

function init(self)
	self.acid = {}
	self.time = 0
	self.acidtile = 13
	parse(self)
end

local ACID_TIME = 0.2

local function acidanim(self, dt)
	self.time = self.time + dt

	if self.time >= ACID_TIME then
		self.time = 0
		self.acidtile = self.acidtile + 1
		if self.acidtile > 16 then self.acidtile = 13 end
		for k, v in pairs(self.acid) do
			tilemap.set_tile("#tilemap", "world", self.acid[k].x, self.acid[k].y, self.acidtile)
		end
	end
end

function update(self, dt)
	if data.state == data.STATE_PLAYING then
		acidanim(self, dt)
	end
end




