function init(self)
	msg.post(".", "acquire_input_focus")
	self.enabled = true
end

local function disablenode (self, node)
	gui.set_enabled(node, false)
end

function on_input(self, action_id, action)
	if (action_id == hash("tap") or action_id == hash("scroll")) and action.pressed and self.enabled == true then
		gui.animate(gui.get_node("tutorial"), gui.PROP_COLOR, vmath.vector4(0, 0, 0, 0), gui.EASING_INOUTQUAD, 0.25, 0, disablenode)
		self.enabled = false
	end
end
