local data = require ("main.data")

function init(self)
	self.fired = false
end

function update(self, dt)
	if not self.fired then
		local pos = go.get_position()

		if pos.x < (data.scrollpos.x + 350) then
			self.fired = true
			local missile = factory.create("#missile_factory", pos, nil, {angle = 0, snap = true}, 1)
		end	
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("pos") then
		go.set_position(message.pos)
	end
end

