local data = require "main.data"
local ui = require "main.ui"

function init(self)
	self.node = gui.get_node("container")
	ui.init(self.node)
end

function update(self, dt)
	gui.set_text(gui.get_node("score"), string.format("%05d", data.score)) 
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show") then
		ui.show(self.node)
		data.state = data.STATE_GAMEOVER
	end
end
