local data = require "main.data"

local function disablenode(self, node)
	gui.set_enabled(node, false)
end

function init(self)
	gui.animate(gui.get_node("container"), "color.w", 0, gui.EASING_LINEAR, 0.2, 3, disablenode)
end

function update(self, dt)
	gui.set_text(gui.get_node("score"), string.format("%05d", data.score)) 
	gui.set_scale(gui.get_node("hp"), vmath.vector3(5 - data.hp, 1, 1))
end

function on_message(self, message_id, message, sender)
end

