local data = require "main.data"

function init(self)
	self.groups = {hash("world"), hash("player"), hash("block")}
end

function collide(d1,d2,s1,s2)
	if s1.x > d2.x or s2.x < d1.x then return false end
	if s1.y > d2.y or s2.y < d1.y then return false end

	return true
end

function update(self, dt)
	local target = go.get_position() + vmath.vector3(500,0,0)
	local result = physics.raycast(go.get_position(), target, self.groups)

	local len = result.position.x - go.get_position().x
	go.set_scale(vmath.vector3(len/16, 1, 1))

	if data.state == data.STATE_PLAYING then
		if collide(go.get_position() - vmath.vector3(0,-2,0), result.position + vmath.vector3(0,2,0), data.playerpos + vmath.vector3(-8,-8,0), data.playerpos + vmath.vector3(8,8,0)) then
			msg.post("/common/player", "dead")
			sound.play("main:/sound#laser")
		end
	end

	sprite.set_constant("#sprite", "tint", vmath.vector4(1,1,1,math.random(50, 100) / 100))
end
