local data = require "main.data"

go.property("inputs", 1)
go.property("left", false)
go.property("active", true)

function init(self)
	
	self.count = 0
	if self.left then
		self.on = 90
		self.off = 0
		msg.post("#sprite-r", "disable")
		msg.post("#co-r", "disable")
	else
		self.on = -90
		self.off = 0
		msg.post("#sprite-l", "disable")
		msg.post("#co-l", "disable")
	end

	if not self.active then
		local temp = self.off
		self.off = self.on
		self.on = temp
		go.animate(".", "euler.z", go.PLAYBACK_ONCE_FORWARD, self.off, go.EASING_INOUTQUAD, 0.5)
	end
end

local function toggle(self, enter)
	if enter then self.count = self.count + 1
	else self.count = self.count - 1
	end

	if self.count >= self.inputs then
		go.animate(".", "euler.z", go.PLAYBACK_ONCE_FORWARD, self.on, go.EASING_INQUAD, 0.6)
	else
		go.animate(".", "euler.z", go.PLAYBACK_ONCE_FORWARD, self.off, go.EASING_INQUAD, 0.6)
	end

	if (enter and self.count >= self.inputs) or (not enter and self.count == self.inputs - 1) then
		sound.play("main:/sound#trapdoor")
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("switch") then
		toggle(self, message.enter)
	end	
end

